GLOBAL_RULES = {
    # --- Food & Drinks ---
    "pizza": "Food",
    "burger": "Food",
    "sandwich": "Food",
    "restaurant": "Food",
    "cafe": "Food",
    "coffee": "Food",
    "starbucks": "Food",
    "latte": "Food",
    "beer": "Food",
    "wine": "Food",
    "bar": "Food",
    "pub": "Food",
    "grocery": "Food",
    "supermarket": "Food",

    # --- Transport ---
    "uber": "Transport",
    "taxi": "Transport",
    "cab": "Transport",
    "bus": "Transport",
    "metro": "Transport",
    "subway": "Transport",
    "train": "Transport",
    "railway": "Transport",
    "gas": "Transport",
    "fuel": "Transport",
    "petrol": "Transport",
    "diesel": "Transport",
    "parking": "Transport",
    "toll": "Transport",

    # --- Health & Fitness ---
    "gym": "Health",
    "fitness": "Health",
    "yoga": "Health",
    "pharmacy": "Health",
    "medicine": "Health",
    "drug": "Health",
    "hospital": "Health",
    "clinic": "Health",
    "doctor": "Health",
    "insurance": "Health",

    # --- Shopping ---
    "amazon": "Shopping",
    "walmart": "Shopping",
    "target": "Shopping",
    "mall": "Shopping",
    "store": "Shopping",
    "shop": "Shopping",
    "clothes": "Shopping",
    "apparel": "Shopping",
    "shoes": "Shopping",
    "electronics": "Shopping",
    "gadget": "Shopping",

    # --- Bills & Utilities ---
    "rent": "Bills",
    "mortgage": "Bills",
    "electricity": "Bills",
    "power": "Bills",
    "hydro": "Bills",
    "water": "Bills",
    "utility": "Bills",
    "internet": "Bills",
    "wifi": "Bills",
    "broadband": "Bills",
    "phone": "Bills",
    "mobile": "Bills",
    "sim": "Bills",

    # --- Entertainment ---
    "netflix": "Entertainment",
    "hulu": "Entertainment",
    "prime": "Entertainment",
    "movie": "Entertainment",
    "cinema": "Entertainment",
    "theatre": "Entertainment",
    "concert": "Entertainment",
    "event": "Entertainment",
    "ticket": "Entertainment",
    "game": "Entertainment",
    "xbox": "Entertainment",
    "ps": "Entertainment",
    "steam": "Entertainment",
}
